### ISSUE TITLE
Помоги

### ISSUE THREAD

**Issue by doofzoff** [123jjck/ddplusplus#13]
****Привет друг! Я вообще только сейчас углубляюсь в Шарарам сцену, и вот я могу задавать тупые вопросы, но я просто обязан запустить этот сервер. Я знаю, что шифрование у Шарарама RC4, итак смотри
Откуда мне взять старую базу SWF ведь сейчас все почти приватные сервера закрыты, за исключением xLand, а также за исключением нового OreoLand если память не изменяет.
И кстати, если можешь обнови пожалуйста ссылку на скачку AMS.
Так да, откуда мне взять старую базу SWF?
Надеюсь ты мне поможешь запустить, жду твоего ответа
Спасибо заранее, удачи!

**Comment by PerovXP** [comment]
поставь минимальное/проксирующее флеш-хранилище и не парься

**Comment by 123jjck** [comment]
Старое флеш хранилище https://mega.nz/file/RTgmxIpD#J6w_ZdMHKc-H5njO_kJE0iJo9nwJHOG1anKyk9MMu64 (пароль **ddps_top**)
