### ISSUE TITLE
Дикая помощь

### ISSUE THREAD

**Issue by doofzoff** [123jjck/ddplusplus#14]
Итак, родной, привет опять
Если у тебя есть ВК отправь пожалуйста мне свой ВК, ведь мне нужна твоя помощь
Я всё сделал по инструкции, но заходя на сайт у меня тупо ничего нет, только появляется окно авторизации, я авторизуюсь попадаю на game.php и слева снизу есть две кнопки "Кабинет" и "Выйти", и всё, а везде дальше белый экран, но Flash Player у меня на этом браузере есть, поэтому я наверно дико накосячил. Вот фотография, отправь пожалуйста свой ВК
![image](https://user-images.githubusercontent.com/76518751/130329934-46641f97-1fd2-46c9-92a2-e6fad9eddfe4.png)

Сяб заранее! Удачки!

**Comment by PerovXP** [comment]
base.swf закинь в корень вебсервера

**Comment by 123jjck** [comment]
http://dl.dropboxusercontent.com/s/50efaggrl42xa5q/base.zip?dl=0 
пароль от архива siMA46tDbZc9
скачай и разархивируй файл base.swf в папку C:/xampp/htdocs/
