### ISSUE TITLE
Помощь

### ISSUE THREAD

**Issue by Kuoins** [123jjck/ddplusplus#15]
Можно видео установки плз? Немного затупил с adode server? Можно с файл зилой?

**Comment by 123jjck** [comment]
Привет, есть видео по установке обычного ДД - https://youtu.be/aPqYzFdCpwM
Установка ДД++ аналогична, только не нужно редактировать никакие файлы - просто всё скачать, раскинуть по нужным папкам, установить, импортировать базу данных и готово.
