### ISSUE TITLE
ServerAction

### ISSUE THREAD

**Issue by GulgDev** [123jjck/ddplusplus#17]
Мне понадобилось изучить работу ServerAction, но ServerAction ДейзиДейла очень сильно отличается по структуре от Шарарамовского. Такой вопрос: где найти нормальный исходник? Доступен ли он вообще? Как я могу расшифровать ответ сервера?

**Comment by TheGamerDog** [comment]
Чел, ты... ДД работает на бейзе 2019 года, если ты пытаешься закинуть текущий - ясно что ничего не заработает. На текущий момент в шаре другое шифрование, умный - реверсишь, в другом же случае скачай бейз 2019 года.

**Comment by 123jjck** [comment]
В начале 2019 года в base.swf Шарарама поставили новое шифрование. ServerAction можно расшифровать, взяв код дешифровки из бейза и просто подставив в него зашифрованный XML. 
Вот уже расшифрованный ServerAction на состояние 10.04.22: [https://www.toptal.com/developers/hastebin/usilerehih.xml](https://www.toptal.com/developers/hastebin/usilerehih.xml)
Он несильно отличается по структуре, разве что расположение элементов другое (и они не зашифрованы в RC4, как в ДД, так как теперь шифруется весь ServerAction и в этом нет смысла)
