### ISSUE TITLE
Ссылка

### ISSUE THREAD

**Issue by lipton32** [123jjck/ddplusplus#18]
Ссылка на Adobe Media Server не работает, и да, этот исходник работает с бейзом 2009? Если да, то тогда дай мне написать тебе в ВК, пожалуйста. id: lipton10xd

**Comment by Accoast** [comment]
Нашел [это](http://download.macromedia.com/pub/flashmediaserver/updates/4_5_7/Windows_Release_x64/FlashMediaServer4.5_x64.exe). Вроде работает.

**Comment by 123jjck** [comment]
Привет, обновил в [readme](https://github.com/123jjck/ddplusplus/blob/master/readme.md) ссылки на AMS: добавил последнюю, которую можно найти в открытом доступе 5.0.15, а также версию для Linux.
