### ISSUE TITLE
хелпаните пж)

### ISSUE THREAD

**Issue by zaxar000** [123jjck/ddplusplus#19]
я подключаюсь к серверу с другого пк ( он в этой же сети ) синий экран а потом Потеряно соединение с сервером.
хотя с пк с которого хостится все грузится и очень хорошо играется
кто может хелпаните

**Comment by 123jjck** [comment]
В файле ServerAction.php в таком случае нужно поменять IP-адоес RTMP сервера с "localhost" на локальный IP компьютера внутри сети (строка 59)
