### ISSUE TITLE
Белый экран при запуске

### ISSUE THREAD

**Issue by UnitoGit** [123jjck/ddplusplus#20]
Всё сделал по инструкции, запустил нужные программы, установил базу и воспользовался fs 
ещё накатил хромиум с флэшем и итог это белый экран, где внизу есть "кабинет" и "выйти"
![image](https://user-images.githubusercontent.com/84383235/218748651-019fda2e-a1ae-416a-9821-d915f192d1ea.png)

**Comment by 123jjck** [comment]
Дубликат #14, решение там
