### ISSUE TITLE
Проблема с синим экраном

### ISSUE THREAD

**Issue by Blaing7542** [123jjck/ddplusplus#21]

**Comment by Blaing7542** [comment]
Я сделал всё по инструкции, но всё равно синий экран, также по ссылке http://localhost/items.html, пишется что не найден такой URL. Что делать?

**Comment by Werild** [comment]
> Я сделал всё по инструкции, но всё равно синий экран, также по ссылке http://localhost/items.html, пишется что не найден такой URL. Что делать?

че в инспекте выдаёт?

**Comment by 123jjck** [comment]
Привет! Про items.html - это норма, в ДД++ нет этого списка, так как он устарел. Советую скачать [InstantList JS](https://github.com/123jjck/instantlist) и поменять ссылку на список в файле game.php
