### ISSUE TITLE
Не работают мини игры

### ISSUE THREAD

**Issue by platon151739** [123jjck/ddplusplus#22]
Не работает ни одна мини игра. В fs закинул fs.php и всё что получилось добыть шарофайлом.

**Comment by 123jjck** [comment]
Привет! Что именно происходит при попытке зайти в мини игру? Вылезает хотя бы окно с кнопками "да" и "нет"? Или прлсто игра никак не реагирует при нажатии на мини игру?

**Comment by alexsprokosin** [comment]
здравствуйте у меня тоже не работаю мини игры игра никак не реагирует при нажатии на мини игру
