### ISSUE TITLE
При попытке зайти со второго аккаунта на одном компьютере кикает первый

### ISSUE THREAD

**Issue by alexs131227** [123jjck/ddplusplus#23]
Здравствуйте! у меня такая проблема то что при входе второго игрока первый вылетает и пишет потеряно соединение с сервером помогите пожалуйста
![Снимок экрана (10)](https://github.com/123jjck/ddplusplus/assets/85656039/7ceff458-dd0e-4a40-ba3c-a577ece97dd4)

**Comment by 123jjck** [comment]
Привет! Так и должно быть - это защита от ботов, когда с одного IP-адреса на сервер могут заходить сотни аккаунтов. 

Это можно убрать: в файле main.asc нужно удалить строки с 303 по 308, т.е вот эти:
```js
for (var i = 0; i < application.clients.length; i++) {
        if (application.clients[i].ip == client.ip && client.id !== application.clients[i].id) {
            application.disconnect(application.clients[i]);
            break;
        }
}
``` 
и перезапустить сервер. После этого можно будет заходить с одного компьютера без проблем.
