### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by reginamirkil** [123jjck/ddplusplus#24]
Дарова! Ситуация такова: Когда в первый раз установил дд++, все работало в первый день, но потом пошел синий экран, потеря сервера. Решил переустановить, и такая картина: 
![image](https://github.com/123jjck/ddplusplus/assets/143704747/0248e9b8-563b-4ee5-bdcc-779eb4dc84b4)
Что делать? подскажи плиз

**Comment by 123jjck** [comment]
Привет! Loading error возникает из-за проблем с флеш хранилищем.
В папке htdocs должна быть папка "fs" с . swf файлами игры (либо же с установленным минимальным флеш-хранилищем, которое будет само скачивать эти файлы по мере необходимости)
