### ISSUE TITLE
Непонятки с установкой

### ISSUE THREAD

**Issue by mostwantedcheater** [123jjck/ddplusplus#7]
Привет. Я хотел создать тестовый сервер для фана с друзьяшками. Сделал все по инструкции, но не понял откуда брать базу SWFшек. Я их выкачал с помощью SharaFiles и закинул все по инструкции, но ничего не заработало. Затем я увидел base.swf, который я также скачал, но закинул уже в корень веб-сервера. Появился синий экран, но игра до сих пор не работала. Скажите, пожалуйста, как правильно это сделать? Заранее спасибо.

**Comment by 123jjck** [comment]
Нужно использовать base.swf со старым шифрованием, а также проверить, запущен ли AMS, указан ли правильный IP сервера в ServerAction.php и т.д.
Если не можете найти SWF хранилище - то используйте минимальное флеш храналище в разделе misc, оно будет автоматически при необходимости скачивать свф файлы с сервером sharaball

**Comment by mostwantedcheater** [comment]
Ладно. SWF-хранилище есть, вот где можно взять старый base.swf?

**Comment by 123jjck** [comment]
Самый простой метод - взять с  другого приватного сервера.
Большинство приватных серверов используют один и тот же бейз, потому нет особой разницы.
Например с ШараТеста - скачать с sharatest.ru/base.swf (обычно браузер сам начинает скачку, но если нет, то нажать на CTRL+S и выбрать место сохранение файла) и скопировать в папку htdocs

**Comment by mostwantedcheater** [comment]
Все, вопросов нет, спасибо.
